import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import Header from "./components/Header";
import { Box, Center } from "@chakra-ui/react";

const myfont = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html suppressHydrationWarning lang="ja" className={myfont.className}>
      <body>
        <Provider>
          <Header />
          <Box bgColor={"gray.50"} h="100vh">
            <Center>{children}</Center>
          </Box>
        </Provider>
      </body>
    </html>
  );
}
